# -*- coding: utf-8 -*-
"""Copy of HPC Kernel KM (Beta Signal Level)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GxwyGi5q33lYlyQGI0CVSZh8cKXh91Y8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import rbf_kernel
from scipy.stats import median_abs_deviation
# from IPython.display import display, HTML
from scipy.spatial.distance import cdist
from scipy.optimize import minimize_scalar
from lifelines.utils import concordance_index
from sklearn.model_selection import KFold
import time
from sklearn.model_selection import train_test_split
from lifelines import CoxPHFitter
import os
import json
import sys
from sklearn.preprocessing import StandardScaler

"""Let's try to fit a Trans-Kernel-KM model and compare it to Cox model



# Trans-Kernel-KM helper functions

### RBF kernel
"""

def gaussian_kernel(X1, X2, sigma):
    """Compute Gaussian kernel matrix"""
    dists = cdist(X1, X2, metric='sqeuclidean')
    return np.exp(-dists / (2 * sigma ** 2))

"""## Censoring Function"""
def theta_from_target_by_group_mean(h0, beta, x_mean, target=0.10):
    """
    Compute censoring time parameters.
    
    lambda_g = h0 * exp(beta · x_mean)
    theta_g  = (target/(1-target)) * lambda_g
    
    Returens:
    (lambda_g, theta_g)
    """
    beta = np.asarray(beta, dtype=float)
    x_mean = np.asarray(x_mean, dtype=float)
    lam = float(h0 * np.exp(beta @ x_mean))
    theta = float((target / (1.0 - target)) * lam)
    return lam, theta


"""## Individualized Hazard Function"""

def compute_individualized_hazard(x_i, X_train, Y_train, delta_train,
                                 X_source, Y_source, delta_source,
                                 sigma, lambda_value, apply_loo=True):
    """
    Compute individualized hazard function using kernel-weighted target and source data.

    Parameters:
    x_i: ndarray - feature vector of a single sample
    X_train: ndarray - training feature matrix
    Y_train: ndarray - training survival times
    delta_train: ndarray - training event indicators
    X_source: ndarray - source domain feature matrix
    Y_source: ndarray - source domain survival times
    delta_source: ndarray - source domain event indicators
    sigma: float - kernel bandwidth parameter
    lambda_value: float - source weight parameter
    apply_loo: bool - whether to apply leave-one-out when test sample is in training set

    Returns:
    tuple: (unique_times, hazard_values) - time points and corresponding hazard values
    """
    # Ensure inputs are properly shaped
    x_i = np.atleast_2d(x_i)
    X_train = np.atleast_2d(X_train)
    X_source = np.atleast_2d(X_source)

    # Calculate kernel weights
    K_target = gaussian_kernel(x_i, X_train, sigma).flatten()
    K_source = gaussian_kernel(x_i, X_source, sigma).flatten()

    # Apply Leave-One-Out if requested
    if apply_loo:
        # Find samples very similar to the test sample (likely the same sample)
        # Using a high threshold to identify nearly identical samples
        self_idx = np.where(K_target > 0.999)[0]
        if len(self_idx) > 0:
            # Zero out kernel weights for self (equivalent to removing from training set)
            K_target[self_idx] = 0

    # Get all possible event times
    unique_times = np.sort(np.unique(np.concatenate([Y_train, Y_source])))
    hazard_values = []

    for l, t_l in enumerate(unique_times):
        # Previous time point (t_{ℓ-1})
        t_prev = 0 if l == 0 else unique_times[l-1]

        # Weighted event count in target data at time t_l
        target_events = K_target * (delta_train == 1) * (Y_train == t_l)
        target_events_sum = np.sum(target_events)

        # Weighted event count in source data at time t_l
        source_events = K_source * (delta_source == 1) * (Y_source == t_l)
        source_events_sum = np.sum(source_events) / lambda_value

        # Numerator: weighted event sum
        numerator = target_events_sum + source_events_sum

        # Weighted risk set count in target data at t_prev
        target_at_risk = K_target * (Y_train > t_prev)
        target_at_risk_sum = np.sum(target_at_risk)

        # Weighted risk set count in source data at t_prev
        source_at_risk = K_source * (Y_source > t_prev)
        source_at_risk_sum = np.sum(source_at_risk) / lambda_value

        # Denominator: weighted risk set size
        denominator = target_at_risk_sum + source_at_risk_sum

        # Compute hazard at t_l
        if denominator > 0:
            hazard = numerator / denominator
        else:
            hazard = 0

        hazard_values.append(hazard)

    return unique_times, np.array(hazard_values)

"""## Survival Function


"""

def compute_survival_function(hazard_times, hazard_values):
    """
    Calculate survival function from hazard function

    Args:
        hazard_times: array of time points
        hazard_values: array of hazard values at each time pointI

    Returns:
        tuple: (times, survival_probs) - time points and survival probabilities
    """
    n_times = len(hazard_times)
    # Start with survival prob = 1 at time 0
    survival_probs = np.ones(n_times + 1)
    # Add time 0 to our time points
    times = np.concatenate(([0], hazard_times))

    # Calculate survival probabilities at each time point
    for i in range(n_times):
        # Multiply previous survival prob by (1 - current hazard)
        survival_probs[i+1] = survival_probs[i] * (1 - hazard_values[i])

    # Make sure probabilities stay between 0 and 1
    survival_probs = np.clip(survival_probs, 0, 1)

    return times, survival_probs

"""## C-index Function"""

def compute_c_index_from_survival_curves(survival_curves, Y_true, delta):
    """
    Calculate C-index from predicted survival curves

    Args:
        survival_curves: dict where keys are sample indices and values are (times, probs) tuples
        Y_true: array of observed survival times
        delta: array of event indicators (1=event occurred, 0=censored)

    Returns:
        float: C-index value
    """
    n_samples = len(Y_true)

    # Calculate expected survival time as risk score
    risk_scores = np.zeros(n_samples)

    for i in range(n_samples):
        if i not in survival_curves:
            continue

        times, probs = survival_curves[i]

        # Calculate expected survival time using the area under the curve
        time_diffs = np.diff(times)
        avg_probs = (probs[:-1] + probs[1:]) / 2
        expected_time = np.sum(avg_probs * time_diffs)

        # FIXED: Use expected survival time directly as the risk score
        # Longer expected survival = lower risk
        risk_scores[i] = expected_time

    # Calculate C-index using lifelines or our custom function
    try:
        from lifelines.utils import concordance_index
        c_index = concordance_index(Y_true, risk_scores, delta)
    except ImportError:
        c_index = compute_c_index(Y_true, risk_scores, delta)

    return c_index

"""## K-fold Cross Validation"""

def grid_search_cv(X_train, Y_train, delta_train, X_source, Y_source, delta_source,
                  sigma_grid, lambda_grid, n_folds=5, apply_loo=True, random_state=None):
    """
    Perform grid search with cross-validation to find optimal parameters

    Args:
        X_train: feature matrix of target training data
        Y_train: survival times of target training data
        delta_train: event indicators of target training data
        X_source: feature matrix of source data
        Y_source: survival times of source data
        delta_source: event indicators of source data
        sigma_grid: list of bandwidth parameters to try
        lambda_grid: list of source weight parameters to try
        n_folds: number of cross-validation folds
        apply_loo: whether to apply leave-one-out when computing hazard
        random_state: random seed for reproducibility

    Returns:
        tuple: (best_sigma, best_lambda, best_c_index) - optimal parameters and score
    """
    # Initialize best parameters and score
    best_sigma = None
    best_lambda = None
    best_c_index = 0

    # Create k-fold cross-validation splits
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=random_state)

    # Store results for each parameter combination
    results = []

    # Loop through all parameter combinations
    for sigma in sigma_grid:
        for lambda_value in lambda_grid:
            fold_c_indices = []

            # Perform k-fold cross-validation
            for train_idx, val_idx in kf.split(X_train):
                # Split data into training and validation sets
                X_train_fold = X_train[train_idx]
                Y_train_fold = Y_train[train_idx]
                delta_train_fold = delta_train[train_idx]

                X_val_fold = X_train[val_idx]
                Y_val_fold = Y_train[val_idx]
                delta_val_fold = delta_train[val_idx]

                # Generate survival curves for validation samples
                survival_curves = {}

                for i, x_i in enumerate(X_val_fold):
                    # Compute hazard function with LOO option
                    hazard_times, hazard_values = compute_individualized_hazard(
                        x_i, X_train_fold, Y_train_fold, delta_train_fold,
                        X_source, Y_source, delta_source,
                        sigma, lambda_value, apply_loo=apply_loo
                    )

                    # Convert to survival function
                    times, survival_probs = compute_survival_function(hazard_times, hazard_values)

                    # Store survival curve
                    survival_curves[i] = (times, survival_probs)

                # Compute C-index for this fold
                fold_c_index = compute_c_index_from_survival_curves(
                    survival_curves, Y_val_fold, delta_val_fold
                )

                fold_c_indices.append(fold_c_index)

            # Average C-index across folds
            mean_c_index = np.mean(fold_c_indices)

            # Store results
            results.append({
                'sigma': sigma,
                'lambda': lambda_value,
                'c_index': mean_c_index,
                'fold_scores': fold_c_indices
            })

            print(f"σ={sigma}, λ={lambda_value}: C-index = {mean_c_index:.4f}")

            # Update best parameters if better performance found
            if mean_c_index > best_c_index:
                best_c_index = mean_c_index
                best_sigma = sigma
                best_lambda = lambda_value

    print(f"\nBest parameters: σ={best_sigma}, λ={best_lambda}, C-index={best_c_index:.4f}")

    return best_sigma, best_lambda, best_c_index

"""# Trans-Kernel-KM Model"""

def kernel_weighted_transfer_km(X_source, Y_source, delta_source,
                               X_train_target, Y_train_target, delta_train_target,
                               X_test_target, Y_test_target, delta_test_target,
                               sigma_grid=None, lambda_grid=None,
                               n_folds=5, apply_loo=True, random_state=None):
    """
    Kernel-Weighted Transfer Kaplan-Meier Estimation with Cross-Validated Source Weighting

    Args:
        X_source: feature matrix of source data
        Y_source: survival times of source data
        delta_source: event indicators of source data
        X_target: feature matrix of target data
        Y_target: survival times of target data
        delta_target: event indicators of target data
        sigma_grid: list of bandwidth parameters to search (default: auto-generated)
        lambda_grid: list of source weight parameters to search (default: auto-generated)
        n_folds: number of cross-validation folds
        test_size: proportion of target data to use as test set
        apply_loo: whether to apply leave-one-out when computing hazard (default: True)
        random_state: random seed for reproducibility

    Returns:
        tuple: (best_params, final_model, test_c_index) - optimal parameters, final model and test performance
    """
    # Set random seed for reproducibility
    np.random.seed(random_state)

    # Apply standardization to features
    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()
    X_all = np.vstack([X_source, X_train_target])
    scaler.fit(X_all)
    if X_source.shape[0] > 0:
        X_source = scaler.transform(X_source)
    else:
        X_source = np.empty((0, X_train_target.shape[1]))  # optional fallback
    X_train_target = scaler.transform(X_train_target)
    X_test_target = scaler.transform(X_test_target)

    X_train_target = np.repeat(X_train_target, 10, axis=0)
    Y_train_target = np.repeat(Y_train_target, 10, axis=0)
    delta_train_target = np.repeat(delta_train_target, 10, axis=0)

    perm = np.random.permutation(X_train_target.shape[0])
    X_train_target = X_train_target[perm]
    Y_train_target = Y_train_target[perm]
    delta_train_target = delta_train_target[perm]

    # Generate default parameter grids if not provided
    if sigma_grid is None:
        # Generate sigma grid based on median distance in data
        median_dist = np.median(cdist(X_train_target, X_train_target, metric='euclidean')[np.triu_indices(X_train_target.shape[0], k=1)])
        sigma_grid = [median_dist * factor for factor in [0.1, 0.5, 1.0, 2.0, 5.0]]

    if lambda_grid is None:
        # Generate lambda grid with different source weighting factors
        lambda_grid = [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]

    print("Starting parameter search with grid:")
    print(f"Sigma grid: {sigma_grid}")
    print(f"Lambda grid: {lambda_grid}")
    print(f"Cross-validation: {n_folds} folds")
    print(f"Apply LOO: {apply_loo}")

    # Find optimal parameters through grid search
    best_sigma, best_lambda, best_cv_score = grid_search_cv(
        X_train_target, Y_train_target, delta_train_target,
        X_source, Y_source, delta_source,
        sigma_grid, lambda_grid, n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    # Train final model using best parameters on full training data
    print("\nTraining final model with best parameters...")

    # Generate survival curves for test samples
    test_survival_curves = {}

    for i, x_i in enumerate(X_test_target):
        # Compute hazard function with LOO option
        hazard_times, hazard_values = compute_individualized_hazard(
            x_i, X_train_target, Y_train_target, delta_train_target,
            X_source, Y_source, delta_source,
            best_sigma, best_lambda, apply_loo=apply_loo
        )

        # Convert to survival function
        times, survival_probs = compute_survival_function(hazard_times, hazard_values)

        # Store survival curve
        test_survival_curves[i] = (times, survival_probs)

    # Evaluate final model on test set
    test_c_index = compute_c_index_from_survival_curves(
        test_survival_curves, Y_test_target, delta_test_target
    )

    print(f"Test set C-index: {test_c_index:.4f}")

    # Create final model object (parameters and predict function)
    best_params = {'sigma': best_sigma, 'lambda': best_lambda}

    # Define prediction function for new data
    def predict_survival(X_new, apply_loo_pred=apply_loo):
        """
        Predict survival curves for new samples

        Args:
            X_new: feature matrix for new samples
            apply_loo_pred: whether to apply leave-one-out (default: same as training)

        Returns:
            dict: keys are sample indices, values are (times, probs) tuples
        """
        # Apply the same standardization to new data
        X_new_scaled = predict_survival.scaler.transform(X_new)

        survival_curves = {}

        for i, x_i in enumerate(X_new_scaled):
            # Compute hazard function with LOO option
            hazard_times, hazard_values = compute_individualized_hazard(
                x_i, X_train_target, Y_train_target, delta_train_target,
                X_source, Y_source, delta_source,
                best_sigma, best_lambda, apply_loo=apply_loo_pred
            )

            # Convert to survival function
            times, survival_probs = compute_survival_function(hazard_times, hazard_values)

            # Store survival curve
            survival_curves[i] = (times, survival_probs)

        return survival_curves

    # Create final model as callable function with attached parameters
    final_model = predict_survival
    final_model.params = best_params
    # Store LOO setting in the model
    final_model.apply_loo = apply_loo
    # Store the scaler in the model for future predictions
    final_model.scaler = scaler

    return best_params, final_model, test_c_index

"""# Baseline Model

## Cox Model
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

def fit_cox_model(X_train, Y_train, delta_train, X_test, Y_test, delta_test, col_names=None):
   """
   Fit a Cox Proportional Hazards model and evaluate its performance

   Args:
       X_train: training feature matrix
       Y_train: training survival times
       delta_train: training event indicators
       X_test: test feature matrix
       Y_test: test survival times
       delta_test: test event indicators
       col_names: feature column names

   Returns:
       tuple: (model, c_index) - fitted model and test set C-index
   """
   # Create a DataFrame for the training data
   if col_names is None:
       col_names = [f"X{i+1}" for i in range(X_train.shape[1])]

   train_df = pd.DataFrame(X_train, columns=col_names)
   train_df['time'] = Y_train
   train_df['event'] = delta_train

   # Fit the Cox model
   cph = CoxPHFitter()
   cph.fit(train_df, duration_col='time', event_col='event')

   # Create a DataFrame for the test data
   test_df = pd.DataFrame(X_test, columns=col_names)

   # Predict risk scores
   risk_scores = cph.predict_partial_hazard(test_df)

   # Compute C-index (negative risk scores because higher risk = shorter survival time)
   c_index = concordance_index(Y_test, -risk_scores, delta_test)

   return cph, c_index

"""## Trans-Cox"""

def fit_transfer_cox_model(X_source, Y_source, delta_source,
                          X_train_target, Y_train_target, delta_train_target,
                          X_test_target, Y_test_target, delta_test_target,
                          random_state=None, col_names=None):
   """
   Fit Cox model with transfer learning (simply combining source and target data)

   Args:
       X_source: source feature matrix
       Y_source: source survival times
       delta_source: source event indicators
       X_target: target feature matrix
       Y_target: target survival times
       delta_target: target event indicators
       test_size: proportion of target data to use as test set
       random_state: random seed
       col_names: feature column names

   Returns:
       tuple: (model, c_index) - fitted model and test set C-index
   """

   # Create feature column names if not provided
   if col_names is None:
       col_names = [f"X{i+1}" for i in range(X_source.shape[1])]

   # Create DataFrames
   source_df = pd.DataFrame(X_source, columns=col_names)
   source_df['time'] = Y_source
   source_df['event'] = delta_source

   target_train_df = pd.DataFrame(X_train_target, columns=col_names)
   target_train_df['time'] = Y_train_target
   target_train_df['event'] = delta_train_target

   # Combine source and target training data
   combined_df = pd.concat([source_df, target_train_df])

   # Fit the Cox model on combined data
   cph = CoxPHFitter()
   cph.fit(combined_df, duration_col='time', event_col='event')

   # Create test DataFrame
   test_df = pd.DataFrame(X_test_target, columns=col_names)

   # Predict risk scores
   risk_scores = cph.predict_partial_hazard(test_df)

   # Compute C-index
   c_index = concordance_index(Y_test_target, -risk_scores, delta_test_target)

   return cph, c_index, X_test_target, Y_test_target, delta_test_target

"""
# Multigroup Data Generation"""

def generate_multigroup_data(n_source=1000, n_target=200, n_groups=5, source_mix=None, target_mix=None, distribution_type=None, data_type=None, signal_level=None, seed=111):
    """
    Generate multi-group survival data for transfer learning experiments

    Args:
        n_source: number of source samples
        n_target: number of target samples
        n_groups: number of distinct groups
        source_mix: mixing proportions of groups in source data
        target_mix: mixing proportions of groups in target data
        distribution_type: type of feature distribution ("separate", "overlap", "complete_overlap")
        data_type: distribution of groups ("balanced", "unbalanced")
        signal_level: signal strength level (1-7)
        seed: random seed

    Returns:
        tuple: (X_source, Y_source, delta_source, X_target, Y_target, delta_target, group_labels_source, group_labels_target)
    """
    np.random.seed(seed)
    # Allow generating only source or only target data
    if n_source == 0 and n_target > 0:
      X_source = np.empty((0, 2))
      Y_source = np.array([])
      delta_source = np.array([])
      group_labels_source = []

    if n_target == 0 and n_source > 0:
      X_target = np.empty((0, 2))
      Y_target = np.array([])
      delta_target = np.array([])
      group_labels_target = []

    # Default mixing proportions if not provided
    if data_type == "balanced":
        source_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        target_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        print(f"Using balanced data distribution with target_mix: {target_mix}")
    elif data_type == "unbalanced":
        source_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        target_mix = [0.5, 0.2, 0.3, 0, 0]

        print(f"Using unbalanced data distribution with target_mix: {target_mix}")
    else:
        raise NotImplementedError(f"Data type '{data_type}' not implemented")

    n_features = 2  # Use 2 features for simplicity

    # Ensure mixing proportions sum to 1
    source_mix = np.array(source_mix) / sum(source_mix)
    target_mix = np.array(target_mix) / sum(target_mix)

    # Feature distributions for each group
    if distribution_type == "separate":
        group_distributions = [
            {'mean': [35, 1.5], 'std': [2, 0.4]},
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [65, 3.0], 'std': [4, 0.5]},
            {'mean': [30, 5.0], 'std': [2, 0.5]},
            {'mean': [80, 5.5], 'std': [5, 0.5]}
        ]
        print("Using separate feature distributions with minimal overlap")
    elif distribution_type == "overlap":
        group_distributions = [
            {'mean': [50, 2.0], 'std': [3, 0.5]},   # G1 baseline
            {'mean': [52, 2.2], 'std': [3, 0.5]},   # G2 very close
            {'mean': [48, 1.8], 'std': [3, 0.5]},   # G3 slightly to the left
            {'mean': [65, 5.0], 'std': [4, 0.6]},   # G4 far away
            {'mean': [30, 5.5], 'std': [3, 0.5]}    # G5 separate region
        ]
        print("Using partially overlapping feature distributions")
    elif distribution_type == "complete_overlap":
        group_distributions = [
            {'mean': [50, 2.0], 'std': [3, 0.5]},   # G1 baseline
            {'mean': [50, 2.0], 'std': [3, 0.5]},   # G2 identical
            {'mean': [48, 1.8], 'std': [3, 0.5]},   # G3 slightly to the left
            {'mean': [50, 2.0], 'std': [3, 0.5]},   # G4 identical
            {'mean': [50, 2.0], 'std': [3, 0.5]}    # G5 identical
        ]
        print("Using complete overlap feature distributions (most groups identical)")
    elif distribution_type == "pointtwentyfive":
        group_distributions = [
            {'mean': [46.25, 1.875], 'std': [3, 0.5]},
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [53.75, 2.25], 'std': [3, 0.5]}, 
            {'mean': [45, 2.75], 'std': [3, 0.5]},
            {'mean': [57.5, 2.875], 'std': [3, 0.5]}
        ]
        print("Using pointtwentyfive feature distributions")
    else:
        raise NotImplementedError(f"Distribution type '{distribution_type}' not implemented")

#  # Survival coefficients (betas) for each group based on signal level
#     if isinstance(signal_level, int) and 1 <= signal_level <= 7:
#         # Define 7 different upper bounds
#         upper_bounds = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
#         lower_bound = 0.1  # Fixed lower bound

#         # Get the selected upper bound for current level
#         selected_upper_bound = upper_bounds[signal_level-1]

#         # Generate evenly distributed beta values for 5 groups
#         step = (selected_upper_bound - lower_bound) / 4  # Divide range into 5 even parts
#         second_coef_values_ordered = [lower_bound + step * i for i in range(5)]
#         second_coef_indices = [2, 3, 0, 4, 1]
#         second_coef_values = [second_coef_values_ordered[i] for i in second_coef_indices]

#         # Create complete beta set
#         group_betas = [
#             [-0.05, second_coef_values[0]],
#             [-0.02, second_coef_values[1]],
#             [-0.07, second_coef_values[2]],
#             [-0.01, second_coef_values[3]],
#             [-0.09, second_coef_values[4]]
#         ]
#         # Add detailed beta printing for verification
#         print("Full beta values for each group:")
#         for g in range(n_groups):
#             print(f"  Group {g+1}: beta = {group_betas[g]}")

    # Survival coefficients (betas) for each group based on signal level
    if isinstance(signal_level, int) and 0 <= signal_level <= 7:
        lower_bound = 0.1
        delta = 0.2 #@param {type:"slider", min:0.1, max:1, step:0.1}
        # For signal level 1 to 7, upper bound increases by 0.2 each time
        selected_upper_bound = lower_bound + delta * signal_level

        # Generate 5 evenly spaced values from lower_bound to selected_upper_bound
        second_coef_values_ordered = np.linspace(lower_bound, selected_upper_bound, 5).tolist()

        # Apply your reordering
        second_coef_indices = [2, 3, 0, 4, 1]
        second_coef_values = [second_coef_values_ordered[i] for i in second_coef_indices]

        group_betas = [
            [-0.05, second_coef_values[0]],
            [-0.02, second_coef_values[1]],
            [-0.07, second_coef_values[2]],
            [-0.01, second_coef_values[3]],
            [-0.09, second_coef_values[4]],
        ]
        print("Full beta values for each group:")
        for g in range(n_groups):
            print(f"  Group {g+1}: beta = {group_betas[g]}")

    # Baseline hazards and censoring for each group
    group_baseline_hazards = [0.0005, 0.001, 0.002, 0.0035, 0.005]
    # group_censoring_rates = [0.2, 0.25, 0.35, 0.35, 0.4]
    group_censoring_rates = [0.1, 0.1, 0.1, 0.1, 0.1]


    # Generate source data
    X_source_all = []
    Y_source_all = []
    delta_source_all = []
    group_labels_source = []

    for g in range(n_groups):
        # Calculate number of samples for this group
        n_g = int(n_source * source_mix[g])
        if g == n_groups - 1:  # Adjust last group to ensure total equals n_source
            n_g = n_source - sum(int(n_source * source_mix[i]) for i in range(n_groups-1))

        # Generate features from multivariate normal
        X_g = np.random.normal(
            loc=group_distributions[g]['mean'],
            scale=group_distributions[g]['std'],
            size=(n_g, n_features)
        )

        # Generate survival times based on Cox model
        linear_pred = np.dot(X_g, group_betas[g])
        hazards = group_baseline_hazards[g] * np.exp(linear_pred)
        U = np.random.uniform(0, 1, size=n_g)
        T = -np.log(U) / hazards

        # Generate censoring times
        lam_g, theta_g = theta_from_target_by_group_mean(
            h0=group_baseline_hazards[g],
            beta=group_betas[g],
            x_mean=group_distributions[g]['mean'],
            target=0.10
        )

        C = np.random.exponential(scale=1.0 / theta_g, size=n_g)
        Y = np.minimum(T, C)
        delta = (T <= C).astype(int)

        if n_g > 0:
            censor_rate = float(np.mean(C < T))
            print(f"[CENSOR][Signal_Level] level={signal_level} group={g+1} n={n_g} "
                  f"lambda={lam_g:.8g} theta={theta_g:.8g} rate={censor_rate:.6f}", flush=True)

        # Store data
        X_source_all.append(X_g)
        Y_source_all.append(Y)
        delta_source_all.append(delta)
        group_labels_source.extend([g] * n_g)

    # Combine all source groups
    X_source = np.vstack(X_source_all)
    Y_source = np.concatenate(Y_source_all)
    delta_source = np.concatenate(delta_source_all)

    # Generate target data similarly
    X_target_all = []
    Y_target_all = []
    delta_target_all = []
    group_labels_target = []

    for g in range(n_groups):
        # Calculate number of samples for this group
        n_g = int(n_target * target_mix[g])
        if g == n_groups - 1:  # Adjust last group to ensure total equals n_target
            n_g = n_target - sum(int(n_target * target_mix[i]) for i in range(n_groups-1))

        # Generate features from multivariate normal
        X_g = np.random.normal(
            loc=group_distributions[g]['mean'],
            scale=group_distributions[g]['std'],
            size=(n_g, n_features)
        )

        # Generate survival times based on Cox model
        linear_pred = np.dot(X_g, group_betas[g])
        hazards = group_baseline_hazards[g] * np.exp(linear_pred)
        U = np.random.uniform(0, 1, size=n_g)
        T = -np.log(U) / hazards

        # Generate censoring times
        lam_g, theta_g = theta_from_target_by_group_mean(
            h0=group_baseline_hazards[g],
            beta=group_betas[g],
            x_mean=group_distributions[g]['mean'],
            target=0.10
        )

        C = np.random.exponential(scale=1.0 / theta_g, size=n_g)
        Y = np.minimum(T, C)
        delta = (T <= C).astype(int)

        if n_g > 0:
            censor_rate = float(np.mean(C < T))
            print(f"[CENSOR][Signal_Level] level={signal_level} group={g+1} n={n_g} "
                  f"lambda={lam_g:.8g} theta={theta_g:.8g} rate={censor_rate:.6f}", flush=True)

        # Store data
        X_target_all.append(X_g)
        Y_target_all.append(Y)
        delta_target_all.append(delta)
        group_labels_target.extend([g] * n_g)

    # Combine all target groups
    X_target = np.vstack(X_target_all)
    Y_target = np.concatenate(Y_target_all)
    delta_target = np.concatenate(delta_target_all)

    return (X_source, Y_source, delta_source, X_target, Y_target, delta_target,
            group_labels_source, group_labels_target)

"""# Simulation Result"""

def run_experiment_with_models(X_source, Y_source, delta_source,
                              X_train_target, Y_train_target, delta_train_target,
                              X_test_target, Y_test_target, delta_test_target,
                              group_labels_source, group_labels_train_target, group_labels_test_target,
                              sigma_grid, lambda_grid,
                              n_folds=3, feature_names=None,
                              apply_loo=True, random_state=None):
    """
    Run model experiments on given data comparing three approaches:
    1. Cox (Target Only)
    2. Cox with Naive Transfer
    3. Feature-based Kernel KM (original Trans-Kernel-KM)
    """
    start_time = time.time()

    # Initialize results dictionary
    results = {}

    # Baseline 1: Cox model on target data only
    print("\nFitting Cox model on target data only...")
    cox_model, cox_c_index = fit_cox_model(
        X_train_target, Y_train_target, delta_train_target, X_test_target, Y_test_target, delta_test_target, feature_names
    )
    results["Cox (Target Only)"] = cox_c_index
    print(f"Cox model on target data: C-index = {cox_c_index:.4f}")

    # Baseline 2: Cox model with naive transfer (combined data)
    print("\nFitting Cox model with naive transfer...")
    transfer_cox_model, transfer_cox_c_index, _, _, _ = fit_transfer_cox_model(
        X_source, Y_source, delta_source, X_train_target, Y_train_target, delta_train_target, X_test_target, Y_test_target, delta_test_target,
        random_state=random_state, col_names=feature_names
    )
    results["Cox (Naive Transfer)"] = transfer_cox_c_index
    print(f"Cox model with naive transfer: C-index = {transfer_cox_c_index:.4f}")

    # Baseline 3: Kernel-weighted KM using only target data (no source)
    X_source_empty = np.empty((0, X_train_target.shape[1]))
    Y_source_empty = np.array([])
    delta_source_empty = np.array([])

    best_params_target_only, kw_model_target_only, kw_c_index_target_only = kernel_weighted_transfer_km(
        X_source_empty, Y_source_empty, delta_source_empty,
        X_train_target, Y_train_target, delta_train_target, X_test_target, Y_test_target, delta_test_target,
        sigma_grid=sigma_grid, lambda_grid=[1.0],  # lambda has no effect when no source
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    results["Kernel-weighted KM (Target Only)"] = kw_c_index_target_only
    print(f"Kernel-weighted KM (Target Only): C-index = {kw_c_index_target_only:.4f}")

    # Method 3: Feature-based Kernel KM (original)
    print("\nFitting Feature-based Kernel KM model...")
    feature_params, feature_model, feature_c_index = kernel_weighted_transfer_km(
        X_source, Y_source, delta_source,
        X_train_target, Y_train_target, delta_train_target, X_test_target, Y_test_target, delta_test_target,
        sigma_grid=sigma_grid, lambda_grid=lambda_grid,
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    results["Feature-based KM"] = feature_c_index
    print(f"Feature-based Kernel KM: C-index = {feature_c_index:.4f}")
    print(f"Best parameters: sigma={feature_params['sigma']}, lambda={feature_params['lambda']}")

    # Print total runtime
    end_time = time.time()
    print(f"\nTotal experiment runtime: {end_time - start_time:.2f} seconds")

    return {
        'results': results,
        'models': {
            'cox': cox_model,
            'transfer_cox': transfer_cox_model,
            'kw_target_only': kw_model_target_only,
            'feature_km': feature_model
        },
        'best_params': {
            'feature_km': feature_params
        },
        'data': {
            'X_train': X_train_target, 'Y_train': Y_train_target, 'delta_train': delta_train_target,
            'X_test': X_test_target, 'Y_test': Y_test_target, 'delta_test': delta_test_target,
            'group_labels_train': group_labels_train_target, 'group_labels_test': group_labels_test_target
        }
    }

"""# Recurring Version Loop through all 7"""

if __name__ == "__main__":
    import os
    import sys
    import json

    print("===== Running Multi-Group Transfer Learning Experiment =====")

    # Get SLURM job ID as a unique identifier
    task_id = os.environ.get("SLURM_ARRAY_TASK_ID", "0")  # Default to "0" if not defined
    random_state = int(task_id)  # Use task_id as random seed

    # Define output directory and file path
    output_dir_name = "tlkbetaoverlap" #@param {type:"string"}
    output_dir = f'/scratch/th3220/{output_dir_name}/'
    print(f"Output directory set to: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)


    # Define result prefix parameter that can be edited in Colab
    output_file = os.path.join(output_dir, f'tlkkm_result_{task_id}.json')

    # Check if output file already exists, skip computation if it does
    if os.path.exists(output_file):
        print(f"File {output_file} exists. Stopping the script.", flush=True)
        sys.exit(0)
    else:
        print(f"File does not exist. Continuing the script.", flush=True)

    # Experiment parameter settings
    n_source = 2000
    n_train_target = 50
    n_test_target = 1000
    n_folds = 5 #@param {type:"slider", min:1, max:10, step:1}
    apply_loo = True

    # Data generation control
    data_type = "unbalanced" #@param ["balanced", "unbalanced"]

    # Distribution handle
    distribution_type = "separate" #@param ["separate", "overlap", "complete_overlap", "pointtwentyfive"]

    # Model parameter grid
    param_grid_type = "HPC" #@param ["comprehensive", "testing", "HPC"]

    if param_grid_type == "comprehensive":
        sigma_grid = [0.05, 0.1, 0.2, 0.5]
        lambda_grid = [0.5, 1.0, 2.0]
        print("Using comprehensive parameter grid for thorough model evaluation")
    elif param_grid_type == "testing":
        sigma_grid = [0.1]
        lambda_grid = [1.0]
        print("Using simplified parameter grid for quick testing")
    elif param_grid_type == "HPC":
        # Log-scale grid: 5x5 evenly spaced in log space
        sigma_grid = np.logspace(np.log10(0.1), np.log10(10.0), 5).tolist()
        lambda_grid = np.logspace(np.log10(0.1), np.log10(10.0), 5).tolist()
        print("Using fixed 5x5 log-scale grid for HPC evaluation")
    else:
        raise NotImplementedError(f"Parameter grid type '{param_grid_type}' not implemented")

    # Feature names (for visualization)
    feature_names = ["Age", "Tumor Size"]

    # Dictionary to store results for all signal levels
    all_results = {}

    # Run experiments for all 7 signal levels
    for signal_level in range(0, 8):
        print(f"\n{'='*20} SIGNAL LEVEL {signal_level} {'='*20}")

        # Generate experimental data
        print(f"Generating multi-group simulated data for signal level {signal_level}...")
        X_source, Y_source, delta_source, _, _, _, \
        group_labels_source, _ = generate_multigroup_data(
            n_source=n_source,
            n_target=0,
            distribution_type=distribution_type,
            data_type=data_type,
            signal_level=signal_level,
            seed=random_state+1000
        )
        print(f"Generated source data: {X_source.shape[0]} samples")
        
        _, _, _, X_train_target, Y_train_target, delta_train_target, \
        group_labels_train_target, _ = generate_multigroup_data(
            n_source=0,
            n_target=n_train_target,
            distribution_type=distribution_type,
            data_type=data_type,
            signal_level=signal_level,
            seed=random_state+2000
        )
        print(f"Generated train data: {X_train_target.shape[0]} samples")

        _, _, _, X_test_target, Y_test_target, delta_test_target, \
        group_labels_test_target, _ = generate_multigroup_data(
            n_source=0,
            n_target=n_test_target,
            distribution_type=distribution_type,
            data_type=data_type,
            signal_level=signal_level,
            seed=random_state+3000
        )
        print(f"Generated test data: {X_test_target.shape[0]} samples")

        experiment_results = run_experiment_with_models(
            X_source, Y_source, delta_source,
            X_train_target, Y_train_target, delta_train_target,
            X_test_target, Y_test_target, delta_test_target,
            group_labels_source, group_labels_train_target, group_labels_test_target,
            sigma_grid=sigma_grid, lambda_grid=lambda_grid,
            n_folds=n_folds, feature_names=feature_names,
            apply_loo=apply_loo, random_state=random_state
        )

        results = experiment_results['results']

        # Add simplified results for this signal level
        signal_results = {}
        for key in ['Cox (Target Only)', 'Cox (Naive Transfer)', 'Feature-based KM', 'Kernel-weighted KM (Target Only)', 'Prediction-based KM']:
            if key in results:
                # Convert float64 to Python float
                signal_results[key] = float(results[key])

        # Store in all_results dictionary
        all_results[f"signal_level_{signal_level}"] = signal_results

    # Save combined results to a single file
    with open(output_file, 'w') as f:
        json.dump(all_results, f, indent=4)

    print(f"\nAll results saved to {output_file}")
    print("\nExperiment completed!")