# -*- coding: utf-8 -*-
"""1000test HPC Kernel KM (Target Sample)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g49uPe8wncIvvrD3xDoQhCbCxmLHnqLQ
"""

import os
import sys
import json
import time
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

# ============================================================
# USER CONFIGURATION — edit these before running
# ============================================================
OUTPUT_DIR = "/scratch/th3220/tlktarget/"  # directory where result JSONs will be saved
DATA_TYPE  = "balanced"                     # "balanced" or "unbalanced"
# ============================================================

"""Let's try to fit a Trans-Kernel-KM model and compare it to Cox model

# Trans-Kernel-KM helper functions

### RBF kernel
"""

def gaussian_kernel(X1, X2, sigma):
    """Compute Gaussian kernel matrix"""
    dists = cdist(X1, X2, metric='sqeuclidean')
    return np.exp(-dists / (2 * sigma ** 2))
    
"""## Censoring Function"""
def theta_from_target_by_group_mean(h0, beta, x_mean, target=0.10):
    """
    Compute censoring time parameters.
    
    lambda_g = h0 * exp(beta · x_mean)
    theta_g  = (target/(1-target)) * lambda_g
    
    Returens:
    (lambda_g, theta_g)
    """
    beta = np.asarray(beta, dtype=float)
    x_mean = np.asarray(x_mean, dtype=float)
    lam = float(h0 * np.exp(beta @ x_mean))
    theta = float((target / (1.0 - target)) * lam)
    return lam, theta

"""## Individualized Hazard Function"""

def compute_individualized_hazard(x_i, X_train, Y_train, delta_train,
                                 X_source, Y_source, delta_source,
                                 sigma, lambda_value, apply_loo=True):
    """
    Compute individualized hazard function using kernel-weighted target and source data.

    Parameters:
    x_i: ndarray - feature vector of a single sample
    X_train: ndarray - training feature matrix
    Y_train: ndarray - training survival times
    delta_train: ndarray - training event indicators
    X_source: ndarray - source domain feature matrix
    Y_source: ndarray - source domain survival times
    delta_source: ndarray - source domain event indicators
    sigma: float - kernel bandwidth parameter
    lambda_value: float - source weight parameter
    apply_loo: bool - whether to apply leave-one-out when test sample is in training set

    Returns:
    tuple: (unique_times, hazard_values) - time points and corresponding hazard values
    """
    # Ensure inputs are properly shaped
    x_i = np.atleast_2d(x_i)
    X_train = np.atleast_2d(X_train)
    X_source = np.atleast_2d(X_source)

    # Calculate kernel weights
    K_target = gaussian_kernel(x_i, X_train, sigma).flatten()
    K_source = gaussian_kernel(x_i, X_source, sigma).flatten()

    # Apply Leave-One-Out if requested
    if apply_loo:
        # Find samples very similar to the test sample (likely the same sample)
        # Using a high threshold to identify nearly identical samples
        self_idx = np.where(K_target > 0.999)[0]
        if len(self_idx) > 0:
            # Zero out kernel weights for self (equivalent to removing from training set)
            K_target[self_idx] = 0

    # Get all possible event times
    unique_times = np.sort(np.unique(np.concatenate([Y_train, Y_source])))
    hazard_values = []

    for l, t_l in enumerate(unique_times):
        # Previous time point (t_{ℓ-1})
        t_prev = 0 if l == 0 else unique_times[l-1]

        # Weighted event count in target data at time t_l
        target_events = K_target * (delta_train == 1) * (Y_train == t_l)
        target_events_sum = np.sum(target_events)

        # Weighted event count in source data at time t_l
        source_events = K_source * (delta_source == 1) * (Y_source == t_l)
        source_events_sum = np.sum(source_events) / lambda_value

        # Numerator: weighted event sum
        numerator = target_events_sum + source_events_sum

        # Weighted risk set count in target data at t_prev
        target_at_risk = K_target * (Y_train > t_prev)
        target_at_risk_sum = np.sum(target_at_risk)

        # Weighted risk set count in source data at t_prev
        source_at_risk = K_source * (Y_source > t_prev)
        source_at_risk_sum = np.sum(source_at_risk) / lambda_value

        # Denominator: weighted risk set size
        denominator = target_at_risk_sum + source_at_risk_sum

        # Compute hazard at t_l
        if denominator > 0:
            hazard = numerator / denominator
        else:
            hazard = 0

        hazard_values.append(hazard)

    return unique_times, np.array(hazard_values)

"""## Survival Function


"""

def compute_survival_function(hazard_times, hazard_values):
    """
    Calculate survival function from hazard function

    Args:
        hazard_times: array of time points
        hazard_values: array of hazard values at each time pointI

    Returns:
        tuple: (times, survival_probs) - time points and survival probabilities
    """
    n_times = len(hazard_times)
    # Start with survival prob = 1 at time 0
    survival_probs = np.ones(n_times + 1)
    # Add time 0 to our time points
    times = np.concatenate(([0], hazard_times))

    # Calculate survival probabilities at each time point
    for i in range(n_times):
        # Multiply previous survival prob by (1 - current hazard)
        survival_probs[i+1] = survival_probs[i] * (1 - hazard_values[i])

    # Make sure probabilities stay between 0 and 1
    survival_probs = np.clip(survival_probs, 0, 1)

    return times, survival_probs

"""## C-index Function"""

def compute_c_index_from_survival_curves(survival_curves, Y_true, delta):
    """
    Calculate C-index from predicted survival curves

    Args:
        survival_curves: dict where keys are sample indices and values are (times, probs) tuples
        Y_true: array of observed survival times
        delta: array of event indicators (1=event occurred, 0=censored)

    Returns:
        float: C-index value
    """
    n_samples = len(Y_true)

    # Calculate expected survival time as risk score
    risk_scores = np.zeros(n_samples)

    for i in range(n_samples):
        if i not in survival_curves:
            continue

        times, probs = survival_curves[i]

        if len(times) < 2 or len(probs) < 2 or np.any(np.isnan(probs)):
            risk_scores[i] = 0  # or np.nan
            continue

        # Expected survival time = area under the survival curve
        time_diffs = np.diff(times)
        avg_probs = (probs[:-1] + probs[1:]) / 2
        expected_time = np.sum(avg_probs * time_diffs)

        risk_scores[i] = expected_time

    try:
        c_index = concordance_index(Y_true, risk_scores, delta)
    except ZeroDivisionError:
        print("Warning: No admissible pairs for C-index. Returning NaN.")
        c_index = np.nan

    return c_index

"""## K-fold Cross Validation"""

def grid_search_cv(X_train, Y_train, delta_train, X_source, Y_source, delta_source,
                  sigma_grid, lambda_grid, n_folds=5, apply_loo=True, random_state=None):
    """
    Perform grid search with cross-validation to find optimal parameters

    Args:
        X_train: feature matrix of target training data
        Y_train: survival times of target training data
        delta_train: event indicators of target training data
        X_source: feature matrix of source data
        Y_source: survival times of source data
        delta_source: event indicators of source data
        sigma_grid: list of bandwidth parameters to try
        lambda_grid: list of source weight parameters to try
        n_folds: number of cross-validation folds
        apply_loo: whether to apply leave-one-out when computing hazard
        random_state: random seed for reproducibility

    Returns:
        tuple: (best_sigma, best_lambda, best_c_index) - optimal parameters and score
    """
    # Initialize best parameters and score
    best_sigma = None
    best_lambda = None
    best_c_index = 0

    # Create k-fold cross-validation splits
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=random_state)

    # Store results for each parameter combination
    results = []

    # Loop through all parameter combinations
    for sigma in sigma_grid:
        for lambda_value in lambda_grid:
            fold_c_indices = []

            # Perform k-fold cross-validation
            for train_idx, val_idx in kf.split(X_train):
                # Split data into training and validation sets
                X_train_fold = X_train[train_idx]
                Y_train_fold = Y_train[train_idx]
                delta_train_fold = delta_train[train_idx]

                X_val_fold = X_train[val_idx]
                Y_val_fold = Y_train[val_idx]
                delta_val_fold = delta_train[val_idx]

                # Generate survival curves for validation samples
                survival_curves = {}

                for i, x_i in enumerate(X_val_fold):
                    # Compute hazard function with LOO option
                    hazard_times, hazard_values = compute_individualized_hazard(
                        x_i, X_train_fold, Y_train_fold, delta_train_fold,
                        X_source, Y_source, delta_source,
                        sigma, lambda_value, apply_loo=apply_loo
                    )

                    # Convert to survival function
                    times, survival_probs = compute_survival_function(hazard_times, hazard_values)

                    # Store survival curve
                    survival_curves[i] = (times, survival_probs)

                # Compute C-index for this fold
                fold_c_index = compute_c_index_from_survival_curves(
                    survival_curves, Y_val_fold, delta_val_fold
                )

                fold_c_indices.append(fold_c_index)

            # Average C-index across folds
            mean_c_index = np.mean(fold_c_indices)

            # Store results
            results.append({
                'sigma': sigma,
                'lambda': lambda_value,
                'c_index': mean_c_index,
                'fold_scores': fold_c_indices
            })

            print(f"σ={sigma}, λ={lambda_value}: C-index = {mean_c_index:.4f}")

            # Update best parameters if better performance found
            if mean_c_index > best_c_index:
                best_c_index = mean_c_index
                best_sigma = sigma
                best_lambda = lambda_value

    print(f"\nBest parameters: σ={best_sigma}, λ={best_lambda}, C-index={best_c_index:.4f}")

    return best_sigma, best_lambda, best_c_index

"""# Trans-Kernel-KM Model"""

def kernel_weighted_transfer_km(X_source, Y_source, delta_source,
                               X_target, Y_target, delta_target,
                               X_test, Y_test, delta_test,
                               sigma_grid=None, lambda_grid=None,
                               n_folds=5, apply_loo=True, random_state=None):
    """
    Kernel-Weighted Transfer Kaplan-Meier Estimation with Cross-Validated Source Weighting

    Args:
        X_source: feature matrix of source data
        Y_source: survival times of source data
        delta_source: event indicators of source data
        X_target: feature matrix of target data (training)
        Y_target: survival times of target data (training)
        delta_target: event indicators of target data (training)
        X_test: feature matrix of test data
        Y_test: survival times of test data
        delta_test: event indicators of test data
        sigma_grid: list of bandwidth parameters to search (default: auto-generated)
        lambda_grid: list of source weight parameters to search (default: auto-generated)
        n_folds: number of cross-validation folds
        apply_loo: whether to apply leave-one-out when computing hazard (default: True)
        random_state: random seed for reproducibility

    Returns:
        tuple: (best_params, final_model, test_c_index) - optimal parameters, final model and test performance
    """
    # Set random seed for reproducibility
    np.random.seed(random_state)

    # Apply standardization to features
    scaler = StandardScaler()
    X_all = np.vstack([X_source, X_target, X_test])
    scaler.fit(X_all)
    if X_source.shape[0] > 0:
        X_source = scaler.transform(X_source)
    else:
        X_source = np.empty((0, X_target.shape[1]))  # optional fallback
    X_target = scaler.transform(X_target)
    X_test = scaler.transform(X_test)

    # Use complete target data as training set
    X_train, Y_train, delta_train = X_target, Y_target, delta_target

    # Generate default parameter grids if not provided
    if sigma_grid is None:
        # Generate sigma grid based on median distance in data
        median_dist = np.median(cdist(X_train, X_train, metric='euclidean')[np.triu_indices(X_train.shape[0], k=1)])
        sigma_grid = [median_dist * factor for factor in [0.1, 0.5, 1.0, 2.0, 5.0]]

    if lambda_grid is None:
        # Generate lambda grid with different source weighting factors
        lambda_grid = [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]

    print("Starting parameter search with grid:")
    print(f"Sigma grid: {sigma_grid}")
    print(f"Lambda grid: {lambda_grid}")
    print(f"Cross-validation: {n_folds} folds")
    print(f"Apply LOO: {apply_loo}")

    # Find optimal parameters through grid search
    best_sigma, best_lambda, best_cv_score = grid_search_cv(
        X_train, Y_train, delta_train,
        X_source, Y_source, delta_source,
        sigma_grid, lambda_grid, n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    # ===== PATCH START: fallback if no valid parameters found =====
    if best_sigma is None or best_lambda is None or np.isnan(best_cv_score):
        print("All parameter combinations failed. Returning null result.")
        return {'sigma': None, 'lambda': None}, None, None
    # ===== PATCH END =====

    # Train final model using best parameters on full training data
    print("\nTraining final model with best parameters...")

    # Generate survival curves for test samples
    test_survival_curves = {}

    for i, x_i in enumerate(X_test):
        # Compute hazard function with LOO option
        hazard_times, hazard_values = compute_individualized_hazard(
            x_i, X_train, Y_train, delta_train,
            X_source, Y_source, delta_source,
            best_sigma, best_lambda, apply_loo=apply_loo
        )

        # Convert to survival function
        times, survival_probs = compute_survival_function(hazard_times, hazard_values)

        # Store survival curve
        test_survival_curves[i] = (times, survival_probs)

    # Evaluate final model on test set
    test_c_index = compute_c_index_from_survival_curves(
        test_survival_curves, Y_test, delta_test
    )

    print(f"Test set C-index: {test_c_index:.4f}")

    # Create final model object (parameters and predict function)
    best_params = {'sigma': best_sigma, 'lambda': best_lambda}

    # Define prediction function for new data
    def predict_survival(X_new, apply_loo_pred=apply_loo):
        """
        Predict survival curves for new samples

        Args:
            X_new: feature matrix for new samples
            apply_loo_pred: whether to apply leave-one-out (default: same as training)

        Returns:
            dict: keys are sample indices, values are (times, probs) tuples
        """
        # Apply the same standardization to new data
        X_new_scaled = predict_survival.scaler.transform(X_new)

        survival_curves = {}

        for i, x_i in enumerate(X_new_scaled):
            # Compute hazard function with LOO option
            hazard_times, hazard_values = compute_individualized_hazard(
                x_i, X_train, Y_train, delta_train,
                X_source, Y_source, delta_source,
                best_sigma, best_lambda, apply_loo=apply_loo_pred
            )

            # Convert to survival function
            times, survival_probs = compute_survival_function(hazard_times, hazard_values)

            # Store survival curve
            survival_curves[i] = (times, survival_probs)

        return survival_curves

    # Create final model as callable function with attached parameters
    final_model = predict_survival
    final_model.params = best_params
    # Store LOO setting in the model
    final_model.apply_loo = apply_loo
    # Store the scaler in the model for future predictions
    final_model.scaler = scaler

    return best_params, final_model, test_c_index

"""# Baseline Model

## Cox Model
"""

def fit_cox_model(X_train, Y_train, delta_train, X_test, Y_test, delta_test, col_names=None):
   """
   Fit a Cox Proportional Hazards model and evaluate its performance

   Args:
       X_train: training feature matrix
       Y_train: training survival times
       delta_train: training event indicators
       X_test: test feature matrix
       Y_test: test survival times
       delta_test: test event indicators
       col_names: feature column names

   Returns:
       tuple: (model, c_index) - fitted model and test set C-index
   """
   # Create a DataFrame for the training data
   if col_names is None:
       col_names = [f"X{i+1}" for i in range(X_train.shape[1])]

   train_df = pd.DataFrame(X_train, columns=col_names)
   train_df['time'] = Y_train
   train_df['event'] = delta_train

   # Fit the Cox model
   cph = CoxPHFitter()
   cph.fit(train_df, duration_col='time', event_col='event')

   # Create a DataFrame for the test data
   test_df = pd.DataFrame(X_test, columns=col_names)

   # Predict risk scores
   risk_scores = cph.predict_partial_hazard(test_df)

   # Compute C-index (negative risk scores because higher risk = shorter survival time)
   c_index = concordance_index(Y_test, -risk_scores, delta_test)

   return cph, c_index

"""## Trans-Cox"""

def fit_transfer_cox_model(X_source, Y_source, delta_source,
                          X_target, Y_target, delta_target,
                          X_test, Y_test, delta_test,
                          random_state=None, col_names=None):
   """
   Fit Cox model with transfer learning (simply combining source and target data)

   Args:
       X_source: source feature matrix
       Y_source: source survival times
       delta_source: source event indicators
       X_target: target feature matrix (training data)
       Y_target: target survival times (training data)
       delta_target: target event indicators (training data)
       X_test: test feature matrix
       Y_test: test survival times
       delta_test: test event indicators
       random_state: random seed
       col_names: feature column names

   Returns:
       tuple: (model, c_index) - fitted model and test set C-index
   """
   # Create feature column names if not provided
   if col_names is None:
       col_names = [f"X{i+1}" for i in range(X_source.shape[1])]

   # Create DataFrames
   source_df = pd.DataFrame(X_source, columns=col_names)
   source_df['time'] = Y_source
   source_df['event'] = delta_source

   target_train_df = pd.DataFrame(X_target, columns=col_names)
   target_train_df['time'] = Y_target
   target_train_df['event'] = delta_target

   # Combine source and target training data
   combined_df = pd.concat([source_df, target_train_df])

   # Fit the Cox model on combined data
   cph = CoxPHFitter()
   cph.fit(combined_df, duration_col='time', event_col='event')

   # Create test DataFrame
   test_df = pd.DataFrame(X_test, columns=col_names)

   # Predict risk scores
   risk_scores = cph.predict_partial_hazard(test_df)

   # Compute C-index
   c_index = concordance_index(Y_test, -risk_scores, delta_test)

   return cph, c_index

"""
# Multigroup Data Generation"""

def generate_multigroup_data(n_source=1000, n_target=200, n_test=None, n_groups=5,
                             source_mix=None, target_mix=None, test_mix=None,
                             distribution_type=None, data_type=None,
                             signal_strength=None, feature_spread=None, seed=111):
    """
    Generate multi-group survival data for transfer learning experiments

    Args:
        n_source: number of source samples
        n_target: number of target samples
        n_test: number of independent test samples (if None, no test set generated)
        n_groups: number of distinct groups
        source_mix: mixing proportions of groups in source data
        target_mix: mixing proportions of groups in target data
        test_mix: mixing proportions of groups in test data (if None, uses target_mix)
        distribution_type: type of feature distribution ("separate", "overlap", "complete_overlap")
        data_type: distribution of groups ("balanced", "unbalanced")
        signal_strength: signal strength level ("strong", "weak")
        feature_spread: scaling factor for group feature separation
        seed: random seed

    Returns:
        tuple: If n_test is None: (X_source, Y_source, delta_source, X_target, Y_target, delta_target, group_labels_source, group_labels_target)
               If n_test is not None: (X_source, Y_source, delta_source, X_target, Y_target, delta_target, X_test, Y_test, delta_test, group_labels_source, group_labels_target, group_labels_test)
    """
    np.random.seed(seed)

    # Default mixing proportions if not provided
    if data_type == "balanced":
        source_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        target_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        print(f"Using balanced data distribution with target_mix: {target_mix}")
    elif data_type == "unbalanced":
        source_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        target_mix = [0.5, 0.2, 0.3, 0, 0]
        print(f"Using unbalanced data distribution with target_mix: {target_mix}")
    else:
        raise NotImplementedError(f"Data type '{data_type}' not implemented")

    # Use target_mix for test_mix if not specified
    if test_mix is None:
        test_mix = target_mix.copy()

    n_features = 2  # Use 2 features for simplicity

    # Ensure mixing proportions sum to 1
    source_mix = np.array(source_mix) / sum(source_mix)
    target_mix = np.array(target_mix) / sum(target_mix)
    test_mix = np.array(test_mix) / sum(test_mix)

    # Feature distributions for each group
    base_mean = np.array([50, 2.0])
    offsets = [
        [-15, -0.5],  # Group 1 offset
        [0, 0],       # Group 2 offset (no deviation from base)
        [15, 1.0],    # Group 3 offset
        [-20, 3.0],   # Group 4 offset
        [30, 3.5]     # Group 5 offset
    ]

    # Apply feature spread scaling if provided, otherwise use default
    if feature_spread is None:
        feature_spread = 1.0  # Default value if not specified

    # Add this line to print feature spread
    print(f"Using feature spread: {feature_spread} for group feature separation")

    # Generate distribution parameters for each group
    group_distributions = []
    for offset in offsets:
        # Calculate mean by adding scaled offset to base mean
        mean = base_mean + feature_spread * np.array(offset)
        # Use same standard deviation for all groups
        group_distributions.append({'mean': mean, 'std': [3, 0.5]})

    # Add this line to print the actual group distributions
    print(f"Group feature distributions:")
    for g in range(n_groups):
        print(f"  Group {g+1}: mean = {group_distributions[g]['mean']}, std = {group_distributions[g]['std']}")

    # Survival coefficients (betas) for each group
    if signal_strength == "strong":
        group_betas = [
            [-0.05, 0.4],
            [-0.02, 0.7],
            [-0.07, 0.1],
            [-0.01, 0.9],
            [-0.09, 0.3]
        ]
        print("Using strong signal strength for survival coefficients")
    elif signal_strength == "weak":
        group_betas = [
            [-0.05, 0.3],
            [-0.02, 0.4],
            [-0.07, 0.1],
            [-0.01, 0.5],
            [-0.09, 0.2]
        ]
        print("Using weak signal strength for survival coefficients")
    elif signal_strength == "very_weak":
        group_betas = [
            [-0.02, 0.15],
            [-0.01, 0.2],
            [-0.03, 0.05],
            [-0.005, 0.25],
            [-0.04, 0.1]
        ]
        print("Using very weak signal strength for survival coefficients")
    elif signal_strength == "extremely_weak":
        group_betas = [
            [-0.01, 0.08],
            [-0.005, 0.1],
            [-0.015, 0.03],
            [-0.003, 0.12],
            [-0.02, 0.05]
        ]
        print("Using extremely weak signal strength for survival coefficients")
    else:
        raise NotImplementedError(f"Signal strength '{signal_strength}' not implemented")

    # Baseline hazards for each group
    group_baseline_hazards = [0.0005, 0.001, 0.002, 0.0035, 0.005]

    def generate_group_data(n_samples, mix_proportions, data_name):
        """Helper function to generate data for source/target/test"""
        X_all = []
        Y_all = []
        delta_all = []
        group_labels = []

        for g in range(n_groups):
            # Calculate number of samples for this group
            n_g = int(n_samples * mix_proportions[g])
            if g == n_groups - 1:  # Adjust last group to ensure total equals n_samples
                n_g = n_samples - sum(int(n_samples * mix_proportions[i]) for i in range(n_groups-1))

            # Skip if no samples for this group
            if n_g <= 0:
                continue

            # Generate features from multivariate normal
            X_g = np.random.normal(
                loc=group_distributions[g]['mean'],
                scale=group_distributions[g]['std'],
                size=(n_g, n_features)
            )

            # Generate survival times based on Cox model
            linear_pred = np.dot(X_g, group_betas[g])
            hazards = group_baseline_hazards[g] * np.exp(linear_pred)
            U = np.random.uniform(0, 1, size=n_g)
            T = -np.log(U) / hazards

            # Generate censoring times
            # Use exponential distribution with rate parameter
            lam_g, theta_g = theta_from_target_by_group_mean(
                h0=group_baseline_hazards[g],
                beta=group_betas[g],
                x_mean=group_distributions[g]['mean'],
                target=0.10
            )
            C = np.random.exponential(scale=1.0 / theta_g, size=n_g)
            Y = np.minimum(T, C)
            delta = (T <= C).astype(int)
            
            if n_g > 0:
                censor_rate = float(np.mean(C < T))
                print(f"[CENSOR][Target_sample_sizes] level={n_target} group={g+1} n={n_g} "
                      f"lambda={lam_g:.8g} theta={theta_g:.8g} rate={censor_rate:.6f}", flush=True)

            # Store data
            X_all.append(X_g)
            Y_all.append(Y)
            delta_all.append(delta)
            group_labels.extend([g] * n_g)

        # Combine all groups
        if X_all:  # Check if we have any data
            X_combined = np.vstack(X_all)
            Y_combined = np.concatenate(Y_all)
            delta_combined = np.concatenate(delta_all)
        else:
            X_combined = np.empty((0, n_features))
            Y_combined = np.array([])
            delta_combined = np.array([])

        return X_combined, Y_combined, delta_combined, group_labels

    # Generate source data
    X_source, Y_source, delta_source, group_labels_source = generate_group_data(
        n_source, source_mix, "source"
    )

    # Generate target data
    X_target, Y_target, delta_target, group_labels_target = generate_group_data(
        n_target, target_mix, "target"
    )

    # Generate test data if requested
    if n_test is not None:
        X_test, Y_test, delta_test, group_labels_test = generate_group_data(
            n_test, test_mix, "test"
        )
        return (X_source, Y_source, delta_source, X_target, Y_target, delta_target,
                X_test, Y_test, delta_test, group_labels_source, group_labels_target, group_labels_test)
    else:
        return (X_source, Y_source, delta_source, X_target, Y_target, delta_target,
                group_labels_source, group_labels_target)

"""# Simulation Result"""

def run_experiment_with_models(X_source, Y_source, delta_source,
                              X_target, Y_target, delta_target,
                              X_test, Y_test, delta_test,
                              group_labels_source, group_labels_target,
                              group_labels_test,
                              sigma_grid, lambda_grid,
                              n_folds=3, feature_names=None,
                              apply_loo=True, random_state=None):
    """
    Run model experiments on given data comparing three approaches:
    1. Cox (Target Only)
    2. Cox with Naive Transfer
    3. Feature-based Kernel KM (original Trans-Kernel-KM)
    """
    start_time = time.time()

    # Use complete target data as training set
    X_train, Y_train, delta_train = X_target, Y_target, delta_target
    group_labels_train = group_labels_target
    # Test data comes from parameters (independent test set)

    # Initialize results dictionary
    results = {}

    # Baseline 1: Cox model on target data only
    print("\nFitting Cox model on target data only...")
    cox_model, cox_c_index = fit_cox_model(
        X_train, Y_train, delta_train, X_test, Y_test, delta_test, feature_names
    )
    results["Cox (Target Only)"] = cox_c_index
    print(f"Cox model on target data: C-index = {cox_c_index:.4f}")

    # Baseline 2: Cox model with naive transfer (combined data)
    print("\nFitting Cox model with naive transfer...")
    transfer_cox_model, transfer_cox_c_index = fit_transfer_cox_model(
        X_source, Y_source, delta_source,
        X_target, Y_target, delta_target,
        X_test, Y_test, delta_test,
        random_state=random_state, col_names=feature_names
    )
    results["Cox (Naive Transfer)"] = transfer_cox_c_index
    print(f"Cox model with naive transfer: C-index = {transfer_cox_c_index:.4f}")

    # Baseline 3: Kernel-weighted KM using only target data (no source)
    X_source_empty = np.empty((0, X_train.shape[1]))
    Y_source_empty = np.array([])
    delta_source_empty = np.array([])

    best_params_target_only, kw_model_target_only, kw_c_index_target_only = kernel_weighted_transfer_km(
        X_source_empty, Y_source_empty, delta_source_empty,
        X_target, Y_target, delta_target,
        X_test, Y_test, delta_test,
        sigma_grid=sigma_grid, lambda_grid=[1.0],  # lambda has no effect when no source
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    results["Kernel-weighted KM (Target Only)"] = kw_c_index_target_only
    print(f"Kernel-weighted KM (Target Only): C-index = {kw_c_index_target_only:.4f}")

    # Method 3: Feature-based Kernel KM (original)
    print("\nFitting Feature-based Kernel KM model...")
    feature_params, feature_model, feature_c_index = kernel_weighted_transfer_km(
        X_source, Y_source, delta_source,
        X_target, Y_target, delta_target,
        X_test, Y_test, delta_test,
        sigma_grid=sigma_grid, lambda_grid=lambda_grid,
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    results["Feature-based KM"] = feature_c_index
    print(f"Feature-based Kernel KM: C-index = {feature_c_index:.4f}")
    print(f"Best parameters: sigma={feature_params['sigma']}, lambda={feature_params['lambda']}")

    # Print total runtime
    end_time = time.time()
    print(f"\nTotal experiment runtime: {end_time - start_time:.2f} seconds")

    return {
        'results': results,
        'models': {
            'cox': cox_model,
            'transfer_cox': transfer_cox_model,
            'feature_km': feature_model
        },
        'best_params': {
            'feature_km': feature_params
        },
        'data': {
            'X_train': X_train, 'Y_train': Y_train, 'delta_train': delta_train,
            'X_test': X_test, 'Y_test': Y_test, 'delta_test': delta_test,
            'group_labels_train': group_labels_train, 'group_labels_test': group_labels_test
        }
    }

"""# Recurring Version Loop"""

if __name__ == "__main__":
    print("===== Running Multi-Group Transfer Learning Experiment with Varying Target Sample Sizes =====")

    # Get SLURM job ID as a unique identifier
    task_id = os.environ.get("SLURM_ARRAY_TASK_ID", "0")  # Default to "0" if not defined
    random_state = int(task_id)  # Use task_id as random seed

    # Output directory from CONFIG
    output_dir = OUTPUT_DIR
    print(f"Output directory set to: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(output_dir, f'tlkkm_target_size_result_{task_id}.json')

    # Check if output file already exists, skip computation if it does
    if os.path.exists(output_file):
        print(f"File {output_file} exists. Stopping the script.", flush=True)
        sys.exit(0)
    else:
        print(f"File does not exist. Continuing the script.", flush=True)

    # Fixed experiment parameters
    n_source = 2000
    n_test = 1000  # Fixed independent test set size
    n_folds = 3 #@param {type:"slider", min:1, max:10, step:1}
    apply_loo = True

    # Data generation control (from CONFIG)
    data_type = DATA_TYPE

    # Signal Strength handle
    signal_strength = "weak" #@param ["strong", "weak", "very_weak", "extremely_weak"]

    # Fixed feature spread value
    feature_spread = 0.25  #@param {type:"slider", min:0, max:2, step:0.25}

    # Model parameter grid
    param_grid_type = "HPC" #@param ["comprehensive", "testing","HPC"]

    if param_grid_type == "comprehensive":
        sigma_grid = [0.05, 0.1, 0.2, 0.5]
        lambda_grid = [0.5, 1.0, 2.0]
        print("Using comprehensive parameter grid for thorough model evaluation")
    elif param_grid_type == "testing":
        sigma_grid = [0.1]
        lambda_grid = [1.0]
    elif param_grid_type == "HPC":
        # Log-scale grid: 5x5 evenly spaced in log space
        sigma_grid = np.logspace(np.log10(0.1), np.log10(1.0), 5).tolist()
        lambda_grid = np.logspace(np.log10(1.0), np.log10(10.0), 5).tolist()
        print("Using fixed 5x5 log-scale grid for HPC evaluation")
    else:
        raise NotImplementedError(f"Parameter grid type '{param_grid_type}' not implemented")

    # Feature names (for visualization)
    feature_names = ["Age", "Tumor Size"]

    # Dictionary to store results for all target sample sizes
    all_results = {}

    # Define target sample sizes to explore
    target_sample_sizes = [50, 100, 200, 400, 800, 1600]

    # Generate independent test set once (shared across all experiments)
    print("Generating independent test set...")
    _, _, _, X_test, Y_test, delta_test, _, group_labels_test = generate_multigroup_data(
        n_source=0,  # No source data needed for test set
        n_target=n_test,  # Use n_target parameter for test set size
        data_type=data_type,
        signal_strength=signal_strength,
        feature_spread=feature_spread,
        seed=random_state + 9999  # Different seed for test set to ensure independence
    )
    print(f"Generated independent test set: {X_test.shape[0]} samples")

    # Run experiments for all target sample sizes
    for n_target in target_sample_sizes:
        print(f"\n{'='*20} TARGET SAMPLE SIZE {n_target} {'='*20}")

        # Generate experimental data (source + target for training)
        print(f"Generating multi-group simulated data with target sample size {n_target}...")
        X_source, Y_source, delta_source, X_target, Y_target, delta_target, \
        group_labels_source, group_labels_target = generate_multigroup_data(
            n_source=n_source,
            n_target=n_target,  # Pass the varying target sample size
            data_type=data_type,
            signal_strength=signal_strength,
            feature_spread=feature_spread,  # Use fixed feature spread
            seed=random_state
        )

        print(f"Generated source data: {X_source.shape[0]} samples")
        print(f"Generated target data: {X_target.shape[0]} samples")

        # Run model experiments
        experiment_results = run_experiment_with_models(
            X_source, Y_source, delta_source,
            X_target, Y_target, delta_target,
            X_test, Y_test, delta_test,  # Add independent test set
            group_labels_source, group_labels_target,
            group_labels_test,  # Add test set labels
            sigma_grid=sigma_grid, lambda_grid=lambda_grid,
            n_folds=n_folds, feature_names=feature_names,  # Remove test_size
            apply_loo=apply_loo, random_state=random_state
        )

        results = experiment_results['results']

        # Add simplified results for this target sample size
        size_results = {}
        for key in ['Cox (Target Only)', 'Cox (Naive Transfer)', 'Feature-based KM', 'Kernel-weighted KM (Target Only)']:
            if key in results:
                # Convert float64 to Python float
                size_results[key] = float(results[key])

        # Store in all_results dictionary
        all_results[f"target_size_{n_target}"] = size_results

    # Save combined results to a single file
    with open(output_file, 'w') as f:
        json.dump(all_results, f, indent=4)

    # print(f"\nAll results saved to {output_file}")
    print("\nExperiment completed!")
