# -*- coding: utf-8 -*-
"""trans_kerkm_demo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iD5HMgU08i5X3aI9z2pNCohy_skvXmQP
"""



# -*- coding: utf-8 -*-
"""
trans_kerkm_demo.py
-------------------
Self-contained demo of the Trans-KerKM estimator.

This script is a simplified, single-run version of the full HPC experiment
(Setting 2b: signal level sweep, imbalanced target mixture).
All core functions are copied verbatim from Model: Trans-KerKM, with one
exception: the np.repeat data-augmentation block inside

Fixed setup:
  - 5 latent subgroups
  - distribution_type = "separate"  (as in HPC experiments)
  - data_type        = "unbalanced" (target_mix = [0.5, 0.2, 0.3, 0, 0])
  - signal_level     = 4
  - n_source         = 2000, n_train_target = 50, n_test_target = 500
  - 3-fold CV on a 2x2 (sigma, lambda) log-scale grid
  - Random seed = 2026

Output:
  C-index table comparing four methods:
      Trans-KerKM | Target-KerKM | Pool-Cox | Target-Cox
"""

# Uncomment the line below if running in Google Colab or a fresh environment:
!pip install numpy scipy scikit-learn lifelines

import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist
from lifelines.utils import concordance_index
from lifelines import CoxPHFitter
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
import time

# =============================================================================
# Core functions — copied verbatim from Model: Trans-KerKM
# =============================================================================

def gaussian_kernel(X1, X2, sigma):
    """Compute Gaussian (RBF) kernel matrix.

    Parameters
    ----------
    X1 : ndarray of shape (n1, d)
    X2 : ndarray of shape (n2, d)
    sigma : float
        Bandwidth parameter. Larger sigma = wider neighborhood.

    Returns
    -------
    K : ndarray of shape (n1, n2)
        K[i, j] = exp(-||X1[i] - X2[j]||^2 / (2 * sigma^2))
    """
    dists = cdist(X1, X2, metric='sqeuclidean')
    return np.exp(-dists / (2 * sigma ** 2))


def theta_from_target_by_group_mean(h0, beta, x_mean, target=0.10):
    """Compute exponential censoring rate to achieve a target censoring fraction.

    Given a Cox subgroup with baseline hazard h0 and coefficient vector beta,
    the subgroup event rate is lambda_g = h0 * exp(beta · x_mean).
    We calibrate the censoring rate theta_g so that
        P(C < T | G = g) = target,
    which gives theta_g = (target / (1 - target)) * lambda_g.

    Parameters
    ----------
    h0 : float
        Subgroup-specific baseline hazard.
    beta : array-like of shape (d,)
        Subgroup-specific coefficient vector.
    x_mean : array-like of shape (d,)
        Subgroup mean covariate vector used for calibration.
    target : float
        Desired censoring fraction (default 0.10).

    Returns
    -------
    lam : float
        Subgroup event rate lambda_g = h0 * exp(beta · x_mean).
    theta : float
        Exponential censoring rate theta_g.
    """
    beta = np.asarray(beta, dtype=float)
    x_mean = np.asarray(x_mean, dtype=float)
    lam = float(h0 * np.exp(beta @ x_mean))
    theta = float((target / (1.0 - target)) * lam)
    return lam, theta


def compute_individualized_hazard(x_i, X_train, Y_train, delta_train,
                                  X_source, Y_source, delta_source,
                                  sigma, lambda_value, apply_loo=True):
    """Estimate the discrete-time hazard function for a single target point x_i.

    Implements Equations (3.1)-(3.3) of the paper. For each observed event
    time t_l, the kernel-weighted event count D^{(-i)}(t_l | x_i) and
    kernel-weighted risk set R^{(-i)}(t_{l-1} | x_i) are computed by
    aggregating over target observations (excluding x_i via LOO) and source
    observations down-weighted by 1/lambda.

    Parameters
    ----------
    x_i : ndarray of shape (d,)
        Covariate vector of the query point.
    X_train : ndarray of shape (n, d)
        Target training covariates.
    Y_train : ndarray of shape (n,)
        Target observed times Y = min(T, C).
    delta_train : ndarray of shape (n,)
        Target event indicators delta = 1{T <= C}.
    X_source : ndarray of shape (m, d)
        Source covariates.
    Y_source : ndarray of shape (m,)
        Source observed times.
    delta_source : ndarray of shape (m,)
        Source event indicators.
    sigma : float
        Kernel bandwidth.
    lambda_value : float
        Global source down-weighting parameter (lambda >= 1).
        lambda = 1: naive pooling. lambda -> inf: target-only.
    apply_loo : bool
        If True, exclude x_i from its own risk and event counts (LOO correction).

    Returns
    -------
    unique_times : ndarray
        Sorted union of all observed event times from target and source.
    hazard_values : ndarray
        Estimated discrete hazard h_hat(t_l | x_i) at each time point.
    """
    x_i = np.atleast_2d(x_i)
    X_train = np.atleast_2d(X_train)
    X_source = np.atleast_2d(X_source)

    K_target = gaussian_kernel(x_i, X_train, sigma).flatten()
    K_source = gaussian_kernel(x_i, X_source, sigma).flatten()

    if apply_loo:
        self_idx = np.where(K_target > 0.999)[0]
        if len(self_idx) > 0:
            K_target[self_idx] = 0

    unique_times = np.sort(np.unique(np.concatenate([Y_train, Y_source])))
    hazard_values = []

    for l, t_l in enumerate(unique_times):
        t_prev = 0 if l == 0 else unique_times[l - 1]

        # Numerator: kernel-weighted event counts (Eq. 3.1)
        target_events_sum = np.sum(K_target * (delta_train == 1) * (Y_train == t_l))
        source_events_sum = np.sum(K_source * (delta_source == 1) * (Y_source == t_l))
        numerator = target_events_sum + source_events_sum / lambda_value

        # Denominator: kernel-weighted risk set (Eq. 3.2)
        target_at_risk_sum = np.sum(K_target * (Y_train > t_prev))
        source_at_risk_sum = np.sum(K_source * (Y_source > t_prev))
        denominator = target_at_risk_sum + source_at_risk_sum / lambda_value

        hazard_values.append(numerator / denominator if denominator > 0 else 0)

    return unique_times, np.array(hazard_values)


def compute_survival_function(hazard_times, hazard_values):
    """Convert discrete hazard estimates to a survival function.

    Implements the product-limit update of Eq. (3.4)-(3.5):
        S_hat(t_l | x_i) = S_hat(t_{l-1} | x_i) * (1 - h_hat(t_l | x_i))
    with S_hat(t_0 | x_i) = 1.

    Parameters
    ----------
    hazard_times : ndarray of shape (L,)
        Ordered event times t_1, ..., t_L.
    hazard_values : ndarray of shape (L,)
        Estimated hazard h_hat(t_l | x_i) at each time point.

    Returns
    -------
    times : ndarray of shape (L+1,)
        Time grid with t_0 = 0 prepended.
    survival_probs : ndarray of shape (L+1,)
        Estimated survival probabilities S_hat(t | x_i).
    """
    n_times = len(hazard_times)
    survival_probs = np.ones(n_times + 1)
    times = np.concatenate(([0], hazard_times))

    for i in range(n_times):
        survival_probs[i + 1] = survival_probs[i] * (1 - hazard_values[i])

    survival_probs = np.clip(survival_probs, 0, 1)
    return times, survival_probs


def compute_c_index_from_survival_curves(survival_curves, Y_true, delta):
    """Compute C-index from a collection of individualized survival curves.

    Each curve is summarized by its expected survival time M_i (Eq. 3.6),
    and the risk score is R_i = -M_i (Eq. 3.7) so that higher risk
    corresponds to shorter predicted survival.

    Parameters
    ----------
    survival_curves : dict
        Keys are integer sample indices. Values are (times, probs) tuples.
    Y_true : ndarray of shape (n,)
        Observed times.
    delta : ndarray of shape (n,)
        Event indicators.

    Returns
    -------
    c_index : float
        Harrell's C-index (Eq. 3.8).
    """
    n_samples = len(Y_true)
    risk_scores = np.zeros(n_samples)

    for i in range(n_samples):
        if i not in survival_curves:
            continue
        times, probs = survival_curves[i]
        time_diffs = np.diff(times)
        avg_probs = (probs[:-1] + probs[1:]) / 2
        risk_scores[i] = np.sum(avg_probs * time_diffs)

    return concordance_index(Y_true, risk_scores, delta)


def grid_search_cv(X_train, Y_train, delta_train,
                   X_source, Y_source, delta_source,
                   sigma_grid, lambda_grid,
                   n_folds=5, apply_loo=True, random_state=None):
    """K-fold cross-validated grid search over (sigma, lambda).

    For each candidate pair, fits Trans-KerKM on the training folds and
    evaluates C-index on the held-out fold. Returns the pair with the
    highest mean validation C-index.

    Parameters
    ----------
    X_train, Y_train, delta_train : target training data.
    X_source, Y_source, delta_source : source data (fixed across folds).
    sigma_grid : list of float
        Candidate bandwidth values sigma.
    lambda_grid : list of float
        Candidate source down-weighting values lambda.
    n_folds : int
        Number of CV folds.
    apply_loo : bool
        Whether to apply LOO correction inside the hazard estimator.
    random_state : int or None

    Returns
    -------
    best_sigma : float
    best_lambda : float
    best_c_index : float
        Mean validation C-index at the best (sigma, lambda) pair.
    """
    best_sigma, best_lambda, best_c_index = None, None, 0.0
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=random_state)

    for sigma in sigma_grid:
        for lambda_value in lambda_grid:
            fold_scores = []

            for train_idx, val_idx in kf.split(X_train):
                X_tr = X_train[train_idx]
                Y_tr = Y_train[train_idx]
                d_tr = delta_train[train_idx]
                X_val = X_train[val_idx]
                Y_val = Y_train[val_idx]
                d_val = delta_train[val_idx]

                curves = {}
                for i, x_i in enumerate(X_val):
                    ht, hv = compute_individualized_hazard(
                        x_i, X_tr, Y_tr, d_tr,
                        X_source, Y_source, delta_source,
                        sigma, lambda_value, apply_loo=apply_loo
                    )
                    times, probs = compute_survival_function(ht, hv)
                    curves[i] = (times, probs)

                fold_scores.append(
                    compute_c_index_from_survival_curves(curves, Y_val, d_val)
                )

            mean_score = np.mean(fold_scores)
            print(f"  sigma={sigma:.4f}, lambda={lambda_value:.4f}: "
                  f"CV C-index = {mean_score:.4f}")

            if mean_score > best_c_index:
                best_c_index = mean_score
                best_sigma = sigma
                best_lambda = lambda_value

    print(f"\nBest: sigma={best_sigma:.4f}, lambda={best_lambda:.4f}, "
          f"C-index={best_c_index:.4f}")
    return best_sigma, best_lambda, best_c_index


def kernel_weighted_transfer_km(X_source, Y_source, delta_source,
                                X_train_target, Y_train_target, delta_train_target,
                                X_test_target, Y_test_target, delta_test_target,
                                sigma_grid=None, lambda_grid=None,
                                n_folds=5, apply_loo=True, random_state=None):
    """Trans-KerKM estimator with cross-validated parameter selection.

    Standardizes features using training statistics, selects (sigma*, lambda*)
    by K-fold CV on the target training set, fits the final model on the full
    training set, and evaluates on the test set.

    Note
    ----
    The np.repeat data-augmentation block present in the original HPC script
    has been removed. That block repeated target training rows 10x before CV,
    which violated the LOO guarantee and is not part of the estimator as
    defined in the paper.

    Parameters
    ----------
    X_source, Y_source, delta_source : source domain data.
    X_train_target, Y_train_target, delta_train_target : target training data.
    X_test_target, Y_test_target, delta_test_target : target test data.
    sigma_grid : list of float or None
        If None, uses 5-point log-scale grid [0.1, ..., 10.0].
    lambda_grid : list of float or None
        If None, uses 5-point log-scale grid [0.1, ..., 10.0].
    n_folds : int
    apply_loo : bool
    random_state : int or None

    Returns
    -------
    best_params : dict with keys 'sigma' and 'lambda'.
    final_model : None (placeholder for API consistency with HPC script).
    test_c_index : float
    """
    np.random.seed(random_state)

    scaler = StandardScaler()
    X_all = np.vstack([X_source, X_train_target]) if X_source.shape[0] > 0 else X_train_target
    scaler.fit(X_all)

    X_source_s = scaler.transform(X_source) if X_source.shape[0] > 0 else X_source
    X_train_s = scaler.transform(X_train_target)
    X_test_s = scaler.transform(X_test_target)

    # NOTE: np.repeat block removed (see docstring above)

    if sigma_grid is None:
        sigma_grid = np.logspace(np.log10(0.1), np.log10(10.0), 5).tolist()
    if lambda_grid is None:
        lambda_grid = np.logspace(np.log10(0.1), np.log10(10.0), 5).tolist()

    print(f"  sigma_grid  : {[f'{s:.4f}' for s in sigma_grid]}")
    print(f"  lambda_grid : {[f'{l:.4f}' for l in lambda_grid]}")
    print(f"  CV folds    : {n_folds}")

    best_sigma, best_lambda, _ = grid_search_cv(
        X_train_s, Y_train_target, delta_train_target,
        X_source_s, Y_source, delta_source,
        sigma_grid, lambda_grid,
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )

    test_curves = {}
    for i, x_i in enumerate(X_test_s):
        ht, hv = compute_individualized_hazard(
            x_i, X_train_s, Y_train_target, delta_train_target,
            X_source_s, Y_source, delta_source,
            best_sigma, best_lambda, apply_loo=apply_loo
        )
        times, probs = compute_survival_function(ht, hv)
        test_curves[i] = (times, probs)

    test_c_index = compute_c_index_from_survival_curves(
        test_curves, Y_test_target, delta_test_target
    )
    print(f"Test set C-index: {test_c_index:.4f}")

    best_params = {'sigma': best_sigma, 'lambda': best_lambda}
    final_model = None  # placeholder for API consistency

    return best_params, final_model, test_c_index


# =============================================================================
# Baseline models — copied verbatim from Model: Trans-KerKM
# =============================================================================

def fit_cox_model(X_train, Y_train, delta_train,
                  X_test, Y_test, delta_test, col_names=None):
    """Fit a target-only Cox proportional hazards model.

    Parameters
    ----------
    X_train, Y_train, delta_train : target training data.
    X_test, Y_test, delta_test : test data.
    col_names : list of str or None

    Returns
    -------
    cph : CoxPHFitter
    c_index : float
    """
    if col_names is None:
        col_names = [f"X{i+1}" for i in range(X_train.shape[1])]

    train_df = pd.DataFrame(X_train, columns=col_names)
    train_df['time'] = Y_train
    train_df['event'] = delta_train

    cph = CoxPHFitter()
    cph.fit(train_df, duration_col='time', event_col='event')

    test_df = pd.DataFrame(X_test, columns=col_names)
    risk_scores = cph.predict_partial_hazard(test_df)
    c_index = concordance_index(Y_test, -risk_scores, delta_test)

    return cph, c_index


def fit_transfer_cox_model(X_source, Y_source, delta_source,
                           X_train_target, Y_train_target, delta_train_target,
                           X_test_target, Y_test_target, delta_test_target,
                           random_state=None, col_names=None):
    """Fit a naive pooling Cox model (source + target training data combined).

    Parameters
    ----------
    X_source, Y_source, delta_source : source data.
    X_train_target, Y_train_target, delta_train_target : target training data.
    X_test_target, Y_test_target, delta_test_target : test data.
    random_state : int or None (unused, kept for API consistency)
    col_names : list of str or None

    Returns
    -------
    cph : CoxPHFitter
    c_index : float
    X_test_target, Y_test_target, delta_test_target : passed through for
        API consistency with the HPC script.
    """
    if col_names is None:
        col_names = [f"X{i+1}" for i in range(X_source.shape[1])]

    source_df = pd.DataFrame(X_source, columns=col_names)
    source_df['time'] = Y_source
    source_df['event'] = delta_source

    target_df = pd.DataFrame(X_train_target, columns=col_names)
    target_df['time'] = Y_train_target
    target_df['event'] = delta_train_target

    combined_df = pd.concat([source_df, target_df])

    cph = CoxPHFitter()
    cph.fit(combined_df, duration_col='time', event_col='event')

    test_df = pd.DataFrame(X_test_target, columns=col_names)
    risk_scores = cph.predict_partial_hazard(test_df)
    c_index = concordance_index(Y_test_target, -risk_scores, delta_test_target)

    return cph, c_index, X_test_target, Y_test_target, delta_test_target


# =============================================================================
# Data generation — copied verbatim from Model: Trans-KerKM
# =============================================================================

def generate_multigroup_data(n_source=1000, n_target=200, n_groups=5,
                             source_mix=None, target_mix=None,
                             distribution_type=None, data_type=None,
                             signal_level=None, seed=111):
    """Generate multi-group survival data for transfer learning experiments.

    Copied verbatim from Model: Trans-KerKM. See paper Section 4.1 for the
    full specification of the latent subgroup model.

    Each subgroup g follows a Cox model:
        h_g(t | X) = h_{0,g}(t) exp(X^T beta_g)
    with X | G=g ~ N(mu_g, diag(sigma_g^2)) and
    C | G=g ~ Exp(theta_g) calibrated to give ~10% censoring per subgroup.

    Parameters
    ----------
    n_source : int
    n_target : int
    n_groups : int
    source_mix : list of float or None
    target_mix : list of float or None
    distribution_type : str
        "separate", "overlap", "complete_overlap", or "pointtwentyfive".
    data_type : str
        "balanced": target_mix = source_mix = [0.2]*5.
        "unbalanced": target_mix = [0.5, 0.2, 0.3, 0, 0] (Setting 2b).
    signal_level : int in [0, 7]
        Controls spread of second-covariate coefficients beta_{g,2}.
        At level l: beta_{g,2} in linspace(0.1, 0.1 + 0.2*l, 5).
    seed : int

    Returns
    -------
    X_source, Y_source, delta_source : source domain arrays.
    X_target, Y_target, delta_target : target domain arrays.
    group_labels_source, group_labels_target : list of int subgroup labels.
    """
    np.random.seed(seed)

    if n_source == 0 and n_target > 0:
        X_source = np.empty((0, 2))
        Y_source = np.array([])
        delta_source = np.array([])
        group_labels_source = []

    if n_target == 0 and n_source > 0:
        X_target = np.empty((0, 2))
        Y_target = np.array([])
        delta_target = np.array([])
        group_labels_target = []

    if data_type == "balanced":
        source_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        target_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
    elif data_type == "unbalanced":
        source_mix = [0.2, 0.2, 0.2, 0.2, 0.2]
        target_mix = [0.5, 0.2, 0.3, 0, 0]
    else:
        raise NotImplementedError(f"Data type '{data_type}' not implemented")

    n_features = 2
    source_mix = np.array(source_mix) / sum(source_mix)
    target_mix = np.array(target_mix) / sum(target_mix)

    if distribution_type == "separate":
        group_distributions = [
            {'mean': [35, 1.5], 'std': [2, 0.4]},
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [65, 3.0], 'std': [4, 0.5]},
            {'mean': [30, 5.0], 'std': [2, 0.5]},
            {'mean': [80, 5.5], 'std': [5, 0.5]},
        ]
    elif distribution_type == "overlap":
        group_distributions = [
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [52, 2.2], 'std': [3, 0.5]},
            {'mean': [48, 1.8], 'std': [3, 0.5]},
            {'mean': [65, 5.0], 'std': [4, 0.6]},
            {'mean': [30, 5.5], 'std': [3, 0.5]},
        ]
    elif distribution_type == "complete_overlap":
        group_distributions = [
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [48, 1.8], 'std': [3, 0.5]},
            {'mean': [50, 2.0], 'std': [3, 0.5]},
            {'mean': [50, 2.0], 'std': [3, 0.5]},
        ]
    elif distribution_type == "pointtwentyfive":
        group_distributions = [
            {'mean': [46.25, 1.875], 'std': [3, 0.5]},
            {'mean': [50, 2.0],      'std': [3, 0.5]},
            {'mean': [53.75, 2.25],  'std': [3, 0.5]},
            {'mean': [45, 2.75],     'std': [3, 0.5]},
            {'mean': [57.5, 2.875],  'std': [3, 0.5]},
        ]
    else:
        raise NotImplementedError(f"Distribution type '{distribution_type}' not implemented")

    if isinstance(signal_level, int) and 0 <= signal_level <= 7:
        lower_bound = 0.1
        delta_step = 0.2
        selected_upper_bound = lower_bound + delta_step * signal_level
        second_coef_values_ordered = np.linspace(lower_bound, selected_upper_bound, 5).tolist()
        second_coef_indices = [2, 3, 0, 4, 1]
        second_coef_values = [second_coef_values_ordered[i] for i in second_coef_indices]
        group_betas = [
            [-0.05, second_coef_values[0]],
            [-0.02, second_coef_values[1]],
            [-0.07, second_coef_values[2]],
            [-0.01, second_coef_values[3]],
            [-0.09, second_coef_values[4]],
        ]

    group_baseline_hazards = [0.0005, 0.001, 0.002, 0.0035, 0.005]

    def _generate_split(n, mix):
        X_all, Y_all, delta_all, labels = [], [], [], []
        for g in range(n_groups):
            n_g = int(n * mix[g])
            if g == n_groups - 1:
                n_g = n - sum(int(n * mix[k]) for k in range(n_groups - 1))
            if n_g == 0:
                continue
            X_g = np.random.normal(
                loc=group_distributions[g]['mean'],
                scale=group_distributions[g]['std'],
                size=(n_g, n_features)
            )
            lp = X_g @ np.array(group_betas[g])
            hazards = group_baseline_hazards[g] * np.exp(lp)
            U = np.random.uniform(size=n_g)
            T = -np.log(U) / hazards
            lam_g, theta_g = theta_from_target_by_group_mean(
                h0=group_baseline_hazards[g],
                beta=group_betas[g],
                x_mean=group_distributions[g]['mean'],
                target=0.10
            )
            C = np.random.exponential(scale=1.0 / theta_g, size=n_g)
            Y = np.minimum(T, C)
            d = (T <= C).astype(int)
            X_all.append(X_g)
            Y_all.append(Y)
            delta_all.append(d)
            labels.extend([g] * n_g)
        return (np.vstack(X_all),
                np.concatenate(Y_all),
                np.concatenate(delta_all),
                labels)

    if n_source > 0:
        X_source, Y_source, delta_source, group_labels_source = _generate_split(
            n_source, source_mix)
    if n_target > 0:
        X_target, Y_target, delta_target, group_labels_target = _generate_split(
            n_target, target_mix)

    return (X_source, Y_source, delta_source,
            X_target, Y_target, delta_target,
            group_labels_source, group_labels_target)


# =============================================================================
# Experiment runner
# =============================================================================

def run_experiment(X_source, Y_source, delta_source,
                   X_train, Y_train, delta_train,
                   X_test, Y_test, delta_test,
                   sigma_grid, lambda_grid,
                   n_folds=3, apply_loo=True, random_state=None):
    """Run all four methods and return C-index results.

    Methods
    -------
    Target-Cox   : Cox model on target training data only.
    Pool-Cox     : Cox model on source + target (naive pooling).
    Target-KerKM : Trans-KerKM with empty source (kernel, target only).
    Trans-KerKM  : Proposed method.
    """
    results = {}
    feature_names = ["Age", "Tumor Size"]

    print("\n--- Target-Cox ---")
    _, c = fit_cox_model(X_train, Y_train, delta_train,
                         X_test, Y_test, delta_test, feature_names)
    results["Target-Cox"] = c
    print(f"C-index = {c:.4f}")

    print("\n--- Pool-Cox (naive pooling) ---")
    _, c, _, _, _ = fit_transfer_cox_model(
        X_source, Y_source, delta_source,
        X_train, Y_train, delta_train,
        X_test, Y_test, delta_test,
        random_state=random_state, col_names=feature_names
    )
    results["Pool-Cox"] = c
    print(f"C-index = {c:.4f}")

    print("\n--- Target-KerKM (kernel, target only) ---")
    X_empty = np.empty((0, X_train.shape[1]))
    Y_empty = np.array([])
    d_empty = np.array([])
    _, _, c = kernel_weighted_transfer_km(
        X_empty, Y_empty, d_empty,
        X_train, Y_train, delta_train,
        X_test, Y_test, delta_test,
        sigma_grid=sigma_grid, lambda_grid=[1.0],
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )
    results["Target-KerKM"] = c
    print(f"C-index = {c:.4f}")

    print("\n--- Trans-KerKM (proposed) ---")
    _, _, c = kernel_weighted_transfer_km(
        X_source, Y_source, delta_source,
        X_train, Y_train, delta_train,
        X_test, Y_test, delta_test,
        sigma_grid=sigma_grid, lambda_grid=lambda_grid,
        n_folds=n_folds, apply_loo=apply_loo, random_state=random_state
    )
    results["Trans-KerKM"] = c
    print(f"C-index = {c:.4f}")

    return results


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":

    SEED = 2026

    SIGNAL_LEVEL   = 4
    DISTRIBUTION   = "separate"
    DATA_TYPE      = "unbalanced"
    N_SOURCE       = 1000
    N_TRAIN_TARGET = 50
    N_TEST_TARGET  = 500
    N_FOLDS        = 3

    SIGMA_GRID  = [0.1, 1.0]
    LAMBDA_GRID = [1.0, 2.0]

    print("=" * 60)
    print("Trans-KerKM Demo")
    print("=" * 60)
    print(f"  Setting        : 2b (signal level sweep, imbalanced)")
    print(f"  distribution   : {DISTRIBUTION}")
    print(f"  data_type      : {DATA_TYPE}  "
          f"(target_mix = [0.5, 0.2, 0.3, 0, 0])")
    print(f"  signal_level   : {SIGNAL_LEVEL}")
    print(f"  n_source       : {N_SOURCE}")
    print(f"  n_train_target : {N_TRAIN_TARGET}")
    print(f"  n_test_target  : {N_TEST_TARGET}")
    print(f"  CV folds       : {N_FOLDS}")
    print(f"  sigma_grid     : {[f'{s:.4f}' for s in SIGMA_GRID]}")
    print(f"  lambda_grid    : {[f'{l:.4f}' for l in LAMBDA_GRID]}")
    print(f"  seed           : {SEED}")
    print()

    print("Generating data...")
    X_source, Y_source, delta_source, _, _, _, _, _ = generate_multigroup_data(
        n_source=N_SOURCE, n_target=0,
        distribution_type=DISTRIBUTION, data_type=DATA_TYPE,
        signal_level=SIGNAL_LEVEL, seed=SEED + 1000
    )
    _, _, _, X_train, Y_train, delta_train, _, _ = generate_multigroup_data(
        n_source=0, n_target=N_TRAIN_TARGET,
        distribution_type=DISTRIBUTION, data_type=DATA_TYPE,
        signal_level=SIGNAL_LEVEL, seed=SEED + 2000
    )
    _, _, _, X_test, Y_test, delta_test, _, _ = generate_multigroup_data(
        n_source=0, n_target=N_TEST_TARGET,
        distribution_type=DISTRIBUTION, data_type=DATA_TYPE,
        signal_level=SIGNAL_LEVEL, seed=SEED + 3000
    )
    print(f"  Source : {X_source.shape[0]} obs, event rate {delta_source.mean():.2f}")
    print(f"  Train  : {X_train.shape[0]} obs,  event rate {delta_train.mean():.2f}")
    print(f"  Test   : {X_test.shape[0]} obs,  event rate {delta_test.mean():.2f}")

    t0 = time.time()
    results = run_experiment(
        X_source, Y_source, delta_source,
        X_train, Y_train, delta_train,
        X_test, Y_test, delta_test,
        sigma_grid=SIGMA_GRID, lambda_grid=LAMBDA_GRID,
        n_folds=N_FOLDS, apply_loo=True, random_state=SEED
    )
    elapsed = time.time() - t0

    print()
    print("=" * 60)
    print("Results Summary")
    print("=" * 60)
    print(f"{'Method':<25} {'C-index':>10}")
    print("-" * 36)
    for method in ["Trans-KerKM", "Target-KerKM", "Pool-Cox", "Target-Cox"]:
        marker = " <-- proposed" if method == "Trans-KerKM" else ""
        print(f"{method:<25} {results[method]:>10.4f}{marker}")
    print("=" * 60)
    print(f"\nTotal runtime: {elapsed:.1f}s")
    print()
    print("Note: Single-run result (seed=2025), 2x2 parameter grid.")
    print("See paper Section 4 for full Monte Carlo results (100 replicates,")
    print("5x5 grid, 5-fold CV).")